[project]
name = "ComfyUI_Simple_Qwen3-VL-gguf"
description = "ComfyUI node for Qwen3-VL and other GGUF VL models via llama.cpp llama-server HTTP API"
version = "4.0"
license = {file = "LICENSE"}
dependencies = ["pillow", "json_repair", "colorama", "opencv-python", "av"]

[project.urls]
Repository = "https://github.com/KLL535/ComfyUI_Simple_Qwen3-VL-gguf"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "kll535"
DisplayName = "ComfyUI_Simple_Qwen3-VL-gguf"
Icon = ""
